name: "Vprofile IAC"
on:
  push:
    branches:
      # - main 
      # - stage 
      - "**"
    paths:
      # So any changes happen in this folder in any sub folder inside that.
      # And if the branch is stage or main, and if the action is pushed, all these things matches,
      # then the workflow will get triggered.
      - terraform/** 
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

env:
  # credentials for deployment to AWS 
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

  # S3 Bucket for Terraform state
  BUCKET_TF_STATE: ${{secrets.BUCKET_TF_STATE}}
  AWS_REGION: ap-southeast-1
  EKS_CLUSTER: vprofile-eks

# workflow must have jobs, and there are many steps under it. 
jobs:
  terraform:
    name: "Apply terraform code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: setup terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.3
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform Fmt 
        run: terraform fmt -check
        id: fmt 

      - name: Terraform Validate
        run: terraform validate
        id: validate
      
      - name: Terraform Plan
        run: terraform plan -no-color -input=false -out plainfile
        id: plan
        continue-on-error: true
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1 # stop the execution exit, close this one
      
      # - name: Terraform Apply
      #   run: terraform apply
      #   id: apply   